### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by liuliuliuqinrui** [KuoHaoZeng/Interactive_Visual_Navigation#3]
Hi , thank u for u open your code , it is very wonderful , 
 but  i meet a problem ,when i run "allenact -s 23456 configs/ithor_ObsNav/obstacles_nav_rgbdk_vNIE.py -c pretrained_model_ckpts/model.pth --eval"
The error  is: TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
  File "/home/csuu/miniconda3/envs/lqr/bin/allenact", line 8, in <module>
    sys.exit(main())
  File "/home/csuu/miniconda3/envs/lqr/lib/python3.6/site-packages/allenact/main.py", line 382, in main
    cfg, srcs = load_config(args)
  File "/home/csuu/miniconda3/envs/lqr/lib/python3.6/site-packages/allenact/main.py", line 319, in load_config
    module = importlib.import_module(module_path)
  File "/home/csuu/miniconda3/envs/lqr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/csuu/lqr/Interactive_Visual_Navigation/configs/ithor_ObsNav/obstacles_nav_rgbdk_vNIE.py", line 12, in <module>
    from interactive_navigation.sensors import (
  File "/home/csuu/lqr/Interactive_Visual_Navigation/interactive_navigation/sensors.py", line 18, in <module>
    class RGBSensorThor(RGBSensor[IThorEnvironment, Task[IThorEnvironment]]):

Can u tell me how to solve the problem  thank u!

**Comment by Xiaoyao-Li** [comment]
Has someone solved this issue? Additionally, I also encountered a similar problem as #4 before i meet this one.
